### ISSUE TITLE
Graph fails on name conflicts across namespaces

### ISSUE THREAD

**Issue by dgovil** [AcademySoftwareFoundation/MaterialX#1871]
I was hitting a bug where some code was passing EMPTY_STRING to the node creation function. This is meant to generate a name that is unique to this node. 

However if I create most of my nodes within a node graph, and then create a node outside the graph, the names will conflict. I'll get two `node1` nodes. 

While my assumption is that nodes are namespaced by their container, this appears to still cause issues if the output material tries to connect to the output of node1. 

The graph then fails because it is unsure which of the two node1's it should connect to. 

I propose that the auto name algorithm should make the node names conflict free across the full topology OR that the connection algorithm pick the node at the correct namespace level instead.

Here's an example graph that is generated using purely the auto-naming code

```
<?xml version="1.0"?>
<materialx version="1.38">
  <nodegraph name="NG_Material_001">
    <texcoord name="Texture_Coordinate_UV" type="vector2" />
    <multiply name="node1" type="vector2">
      <input name="in1" type="vector2" nodename="Texture_Coordinate_UV" />
      <input name="in2" type="vector2" value="32, 32" />
    </multiply>
    <modulo name="node2" type="vector2">
      <input name="in1" type="vector2" nodename="node1" />
      <input name="in2" type="vector2" value="2, 2" />
    </modulo>
    <extract name="node3" type="float">
      <input name="in" type="vector2" nodename="node2" />
      <input name="index" type="integer" value="0" />
    </extract>
    <floor name="node4" type="float">
      <input name="in" type="float" nodename="node3" />
    </floor>
    <extract name="node5" type="float">
      <input name="in" type="vector2" nodename="node2" />
      <input name="index" type="integer" value="1" />
    </extract>
    <floor name="node6" type="float">
      <input name="in" type="float" nodename="node5" />
    </floor>
    <add name="node7" type="float">
      <input name="in1" type="float" nodename="node4" />
      <input name="in2" type="float" nodename="node6" />
    </add>
    <ifequal name="Checker_Texture_Color" type="color4">
      <input name="value1" type="float" nodename="node7" />
      <input name="value2" type="float" value="1" />
      <input name="in1" type="color4" value="0.8, 0.8, 0.8, 1" />
      <input name="in2" type="color4" value="0.2, 0.2, 0.2, 1" />
    </ifequal>
    <convert name="node8" type="color3">
      <input name="in" type="color4" nodename="Checker_Texture_Color" />
    </convert>
    <oren_nayar_diffuse_bsdf name="Diffuse_BSDF_BSDF" type="BSDF">
      <input name="color" type="color3" nodename="node8" />
      <input name="roughness" type="float" value="0" />
    </oren_nayar_diffuse_bsdf>
    <output name="Diffuse_BSDF_BSDF_out" type="BSDF" nodename="Diffuse_BSDF_BSDF" />
  </nodegraph>
  <surface name="node1" type="surfaceshader">
    <input name="bsdf" type="BSDF" output="Diffuse_BSDF_BSDF_out" nodegraph="NG_Material_001" />
  </surface>
  <surfacematerial name="Material_001" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="node1" />
  </surfacematerial>
</materialx>
```

Notice that both the surface node and the multiply node share a name. When I pull this mtlx file into MaterialXView, it errors because the surface material finds the first node with that name, not the first node within the same namespace.

**Comment by kwokcb** [comment]
Hi @dgovil , 
This is considered a valid graph (i.e. unique naming within the "namespace" / graph level) so it seems it's more a problem with logic for code generation and vote to fix that. There are existing unique name matching issues before so adding @niklasharrysson in.

**Comment by dgovil** [comment]
That's good to know, thanks.

**Comment by kwokcb** [comment]
Hey @niklasharrysson , 

I looked at the code a bit and it's the same issue we've discussed before -- that of lack of appriate ShaderGraph context when dealing with `nodegraphs` . i.e. all `ShaderNode`s are in the same `ShaderGraph`. So the node name map will encounter the same node name more than once -- resulting in the symptom encountered [here](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenShader/ShaderGraph.cpp#L123-L132)

```cpp
 // We have a node downstream
        ShaderNode* downstream = getNode(downstreamNode->getName());
        if (downstream && connectingElement)
        {
            ShaderInput* input = downstream->getInput(connectingElement->getName());
            if (!input)
            {
                throw ExceptionShaderGenError("Could not find an input named '" + connectingElement->getName() +
                                              "' on downstream node '" + downstream->getName() + "'");
            }
            input->makeConnection(output);
        }
```
`getNode()` looks up by name which is not unique.

**Comment by niklasharrysson** [comment]
Hey @kwokcb , thanks for investigating. And yes, this will be resolved when we get to updating the ShaderGraph to keep all graph hierarchies.

**Comment by simdvr** [comment]
Hi, we encountered the following similar issue:

Our case: Two nodes with the same name inside two different nodegraphs.
The shader generators fail to create the correct code in this case. Apparently this affects all backends. We confirmed it for MDL, GLSL and OSL.

This might be a general issue in MaterialXGenShader where namespace information is lost before it reaches the individual backends.

A workaround on the application side is to set globally unique node names on the MaterialX document before passing to the shader generator. Of course we would prefer not needing to apply this workaround.

I attached two example mtlx files in the zip: [nodenames-example-mtlx.zip](https://github.com/user-attachments/files/23777271/nodenames-example-mtlx.zip) 
The only difference between them is the naming of the crosshatch node inside the nodegraph (crosshatch1 and crosshatch1 versus crosshatch1 and crosshatch2).
2x-crosshatch-diffName.mtlx -- correct rendering
2x-crosshatch-sameName.mtlx -- broken rendering

This is how it looks in the MaterialXGraphEditor (the blue one is the correct result):
<img width="513" height="400" alt="Image" src="https://github.com/user-attachments/assets/19ab7578-a7f3-4c19-b793-2f90f3b22064" />
<img width="513" height="400" alt="Image" src="https://github.com/user-attachments/assets/68fd399a-5f9a-4906-8b63-17e2fd4307c9" />

**Comment by kwokcb** [comment]
This looks like it's the same issue : node names created during shader generation are not scoped within graphs (graph is flattened), and also they do not have full pathing information so names will clash.

**Comment by niklasharrysson** [comment]
(copied from Slack thread)

I think there are two separate issues that could be fixed:

One issue is the connection logic where by using only string names to reference another node it's easy to get into conflicts. We should probably change this to using pointers or paths (or some specific reference/path class similar to `UsdPath`) to resolve this. A related issue with using node name strings is that if a node is renamed you need to find and update any connections to the node as well, otherwise the network gets broken.

The other issue is in shader generation, where the graphs are flattended, which results in nodes ending up in the same larger graph with the same/conflicting names. I have looked at this briefly, and this flattening is actually not done explicitly, it's a result of how the MaterialXCore API is doing graph traversal. When a network is traversed upstream to find all dependencies, if a NodeGraph is found it continues the traversal into this NodeGraph, so the graph is in effect flattened. It would be much better if we preserved the graph hierarchies. Not only will it reduce the issues with naming conflicts, but it would also help with reducing the number of uniforms exposed on the generated shader, since when a graph is flattened all inputs on all nodes are exposed as top level inputs, generating a lot of shader uniforms.

**Comment by niklasharrysson** [comment]
Issue #1932 is also linked to this.

**Comment by jstone-lucasfilm** [comment]
It looks like the original issue that @dgovil reported here, as well as the related issue noted by @simdvr above, have been addressed by PR #2768, so we can potentially close this task as resolved.

**Comment by simdvr** [comment]
@jstone-lucasfilm I tested the PR with the latest MaterialX built from main, but it does not resolve my issue. The render result is unchanged. 

One difference is that the generated shader code now calls NG_crosshatch_color3 twice instead of once, but both calls use identical parameters. I verified this behavior in both MDL and GLSL. For example, in MDL the generated code looks like this:

```
color crosshatch1_out = NG_crosshatch_color3(geomprop_UV0_out1, crosshatch1_uvtiling, crosshatch1_uvoffset, crosshatch1_thickness, crosshatch1_staggered);
color crosshatch1_out1 = NG_crosshatch_color3(geomprop_UV0_out1, crosshatch1_uvtiling, crosshatch1_uvoffset, crosshatch1_thickness, crosshatch1_staggered);
```

The two crosshatch nodes in the MaterialX graph have different input values though (different uvtiling, uvoffset, thickness, and staggered values).

So the end result is the same as before with 1.39.4.

If the PR fixes the original issue reported by @dgovil I can  create a new issue for my case.

**Comment by jstone-lucasfilm** [comment]
Thanks for the update, @simdvr, and yes -- go ahead and create a separate GitHub Issue for your report, so that we can address it independently.

**Comment by jstone-lucasfilm** [comment]
Following up on this issue, I've confirmed that it has been resolved in #2768, and the related uniform-binding case has been assigned its own issue in #2784.
